### ISSUE TITLE
请问, 校正过程所用语料覆盖面是否要足够大

### ISSUE THREAD

**Issue by MrRace** [bohanli/BERT-flow#1]
看完paper，有些问题请教下。
在训练 BERT-flow，即校正句子语义空间的时候，用的语料是下游任务的语料。
(1)那么是否意味着，对每种下游任务，都需要校正一遍？ 
(2)是否可以做全局校正？比如用Wikipedia的语料进行一次全局校正？
(3)是否可以做到词级分布校正？ 
谢谢！

**Comment by HUSTHY** [comment]
请问这个校正语义空间——从bert的embedding空间变化到标准的高斯潜在空间这个原理你理解清楚了吗？

**Comment by MrRace** [comment]
> 请问这个校正语义空间——从bert的embedding空间变化到标准的高斯潜在空间这个原理你理解清楚了吗？

我的理解是：
拿一定语料进行无监督学习映射函数，该映射将BERT的句子embedding映射到高斯隐语义空间，或者反过来映射。这里的语料默认是full target dataset (train + validation + test)，我的理解是下游任务语料(不带标签)。在学习映射函数的参数期间，BERT的参数固定不变。如果有理解错的，请指正。谢谢！

**Comment by HUSTHY** [comment]
对的，我也是这么理解的。论文里有很几个数学公式理解起来有麻烦。这里的实际训练过程中，是学习映射函数的参数，应该就是把Bert模型原始的参数冻结住。有一个具体实现的问题，就是它给出的训练目标我没有理解清楚，不知道具体实现。这个训练过程中，没有label。从原始的Bert中得到embedding后，怎么计算loss呢？只有有了loss才会有flow模块的参数更新吧？是不是这么理解的？

**Comment by MrRace** [comment]
> 对的，我也是这么理解的。论文里有很几个数学公式理解起来有麻烦。这里的实际训练过程中，是学习映射函数的参数，应该就是把Bert模型原始的参数冻结住。有一个具体实现的问题，就是它给出的训练目标我没有理解清楚，不知道具体实现。这个训练过程中，没有label。从原始的Bert中得到embedding后，怎么计算loss呢？只有有了loss才会有flow模块的参数更新吧？是不是这么理解的？

我的理解是，观测值就是 BERT embedding，目标就是重建出 BERT embedding。生成这个BERT embedding的过程涉及到隐变量，而隐变量服从高斯分布。

**Comment by HUSTHY** [comment]
谢谢，这一点上你说的我明白了，但是这个整体的思路没有理清楚。最后经过这个训练过程，应该是得到一个模型吧。这个模型输入对应的文本信息，得到的embedding应该就是经过变换或者校正了的新的embedding了，它做文本cos相似度计算的时候就要比以前的Sbert效果要好，是这个意思吧？

**Comment by HUSTHY** [comment]
我仔细看看代码看看能不能好好理解论文这个变换的实现和训练的具体过程是什么样的。

**Comment by bohanli** [comment]
Fitting flow with only the train split also outperforms the BERT baseline. Please refer to the updated README.md.
