### ISSUE TITLE
predict 的问题

### ISSUE THREAD

**Issue by WJSAI** [bohanli/BERT-flow#6]
感谢大佬的工作，请问在predict的时候，只有BERT加载训练好的参数，而flow部分虽然之前进行了无监督训练，但是predict的时候似乎并没有加载训好的参数？

部分参数加载如下：
INFO:tensorflow:  name = bert/encoder/layer_11/output/dense/bias:0, shape = (768,), *INIT_FROM_CKPT*
INFO:tensorflow:  name = bert/encoder/layer_11/output/LayerNorm/beta:0, shape = (768,), *INIT_FROM_CKPT*
INFO:tensorflow:  name = bert/encoder/layer_11/output/LayerNorm/gamma:0, shape = (768,), *INIT_FROM_CKPT*
INFO:tensorflow:  name = bert/pooler/dense/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*
INFO:tensorflow:  name = bert/pooler/dense/bias:0, shape = (768,), *INIT_FROM_CKPT*

flow部分并没有加载训好的参数？
INFO:tensorflow:  name = bert/flow/revnet_0/revnet_step_0/actnorm/actnorm_center/b:0, shape = (1, 1, 1, 64)
INFO:tensorflow:  name = bert/flow/revnet_0/revnet_step_0/actnorm/actnorm_scale/logs:0, shape = (1, 1, 1, 64)
INFO:tensorflow:  name = bert/flow/revnet_0/revnet_step_0/additive/nn/conv_block/1_1/W:0, shape = (1, 1, 32, 32)
INFO:tensorflow:  name = bert/flow/revnet_0/revnet_step_0/additive/nn/conv_block/1_1/actnorm/actnorm_center/b:0, shape = (1, 1, 1, 32)
INFO:tensorflow:  name = bert/flow/revnet_0/revnet_step_0/additive/nn/conv_block/1_1/actnorm/actnorm_scale/logs:0, shape = (1, 1, 1, 32)
INFO:tensorflow:  name = bert/flow/revnet_0/revnet_step_0/additive/nn/conv_block/1_2/W:0, shape = (1, 1, 32, 32)

**Comment by zzzhacker** [comment]
@WJSAI  concerned with same issues. I also suggest to  please share inference code on single examples to get the embeddings.

**Comment by WJSAI** [comment]
@zzzhacker 请问大佬解决上面的问题了吗？

**Comment by zzzhacker** [comment]
@WJSAI  Nope still can't figure out the weight things for GLow part. can you share your inference code
